# The full URL of your site
url: "https://paulmartinmcneill.com"
# The subpath of your site if it's hosted in a subdirectory
baseurl: ""

# Site settings
# The title of your site
title: Paul Martin McNeill's Portfolio
email: paulmcneill1989@hotmail.co.uk
# A brief description of your site
description: "Welcome to my portfolio. Here you can find my latest projects and learn more about my expertise in web development, AI, and more."

# Social networks
social:
  - title: twitter
    url: https://x.com/McNeillium
  - title: linkedin
    url: https://www.linkedin.com/in/paul-martin-mcneill-pp
  - title: github
    url: https://github.com/mcneillium
  - title: stack-overflow
    url: https://stackoverflow.com/users/mcneillium
  - title: facebook
    url: https://www.facebook.com/McNeillium/


# Build settings
markdown: kramdown
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
